# Facility dataset configuration for prompt optimization

model:
  name: "openrouter/meta-llama/llama-3.3-70b-instruct"
  api_base: "https://openrouter.ai/api/v1"
  temperature: 0.0
  
dataset:
  adapter_class: "prompt_ops.datasets.facility.FacilityAdapter"
  path: "/Users/justinai/Documents/Code/prompt-ops/dataset/facility-synth/facility_v2_test.json"
  train_size: 0.7
  validation_size: 0.15
  
prompt:
  text: |
    Giving the following message:
    ---
    {{question}}
    ---
    Extract and return a json with the follwoing keys and values:
    - "urgency" as one of `high`, `medium`, `low`
    - "sentiment" as one of `negative`, `neutral`, `positive`
    - "categories" Create a dictionary with categories as keys and boolean values (True/False), where the value indicates whether the category is one of the best matching support category tags from: `emergency_repair_services`, `routine_maintenance_requests`, `quality_and_safety_concerns`, `specialized_cleaning_services`, `general_inquiries`, `sustainability_and_environmental_practices`, `training_and_support_requests`, `cleaning_services_scheduling`, `customer_feedback_and_complaints`, `facility_management_issues`
    Your complete message should be a valid json string that can be read directly and only contain the keys mentioned in the list above. Never enclose it in ```json...```, no newlines, no unnessacary whitespaces.
  inputs: ["question"]
  outputs: ["answer"]

metric:
  class: "facility"
  params: {}

optimization:
  strategy: "light"
  max_rounds: 3
  max_examples_per_round: 5
  max_prompt_length: 2048
