prompt:
  file: "../dataset/facility-synth/facility_prompt_sys.txt"
  inputs: ["question"]
  outputs: ["answer"]

# Dataset configuration
dataset:
  path: "../dataset/facility-synth/facility_v2_test.json"
  input_field: ["fields", "input"]
  golden_output_field: "answer"

# Model configuration
model:
  name: "openrouter/meta-llama/llama-3.3-70b-instruct"

# Metric configuration using our new FacilityMetric
metric:
  class: "facility"
  strict_json: false
  output_field: "answer"

# Optimization settings
optimization:
  strategy: "llama"
