# Core configuration - essential elements only
prompt:
  file: "../dataset/facility-synth/facility_prompt_sys.txt"
  inputs: ["question"]
  outputs: ["answer"]

# Dataset configuration
dataset:
  path: "../dataset/facility-synth/facility_v2_test.json"
  input_field: ["fields", "input"]
  golden_output_field: "answer"

# Model configuration (minimal required settings)
model:
  name: "openrouter/meta-llama/llama-3.3-70b-instruct"

# Metric configuration (simplified but maintains compatibility)
metric:
  class: "standard_json"
  evaluation_mode: "flattened"
  fields: ["urgency", "sentiment", "categories"]
  required_fields: ["urgency", "sentiment", "categories"]

# Optimization settings
optimization:
  strategy: "basic"
